name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # downloads repo code onto runner
      - name: Checkout repo
        uses: actions/checkout@v4

      # downloads pnpm into runner environment
      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      # set up node in runner environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        # install node 22
        # cache: 'pnpm' speeds up installs, reuses previously installed dependencies
        # uses lockfile as cache key
        with:
          node-version: 22
          cache: "pnpm"
        # install dependencies exactly like in lock file
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run linting
        run: pnpm lint

        # if any test fails, workflow fails
      - name: Run tests
        run: pnpm test

      - name: Trivy filesystem scan (HIGH/CRITICAL)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: "fs"
          scan-ref: "."
          severity: "HIGH,CRITICAL"
          exit-code: "1"
